### ISSUE TITLE
Ventilators turn off too fast

### ISSUE THREAD

**Issue by IsaakGroepT** [grmat/amdgpu-fancontrol#1]
Hi 

I'm currently testing your script with my RX580 card and so far it works great, I have adjusted the temp settings to these though:

```
TEMPS=( 50000 60000 75000 85000 )
PWMS=(      0    51   153   255 )
```

I find that the ventilators turn off too fast because the temperatures immediately fall below 60°C after I quit the Unigine benchmark, which makes the card stay at 50°C for a long time (while idle use temps are usually <42°C for me). I've added the 60°C PWMS setting in order to try to let the vents run a bit longer when the card is around 50°C, but it doesn't work.

HYSTERESIS=6000

I read that this setting is used when the temperature is decreasing but in your script it's used for both ways. So I can't use this option in your script to get the behaviour I want.

Can you recommend me how to get the wanted behviour using your script?

Thanks

**Comment by grmat** [comment]
Hi,
thanks for your comment.

`HYSTERESIS` is implemented to prevent annoying fast fluctuations of fan speed, but only used for the case the temperature is decreasing. For the opposite case, in which the temperature (and therefore interpolated PWM value) is increasing, the PWM is raised without influence of the hysteresis value. Also see the first condition in [Line 36](https://github.com/grmat/amdgpu-fancontrol/blob/7602c588a780924313ce73d622b466152221630a/amdgpu-fancontrol#L36): `NEW_PWM > OLD_PWM` (where `>` in bash is `-gt`). Therefore, it should be safe for you to increase the value.

However, I'd recommend to find out at which pwm value your fans start/stop spinning and add an additional temp/pwm value there. It's different for each card and usually not at pwm value 1. It might be possible that the fans are already turned off for a big range of values between 0-51. You can write values manually to `/sys/class/drm/card0/device/hwmon/hwmon0/pwm1` to change speeds. Remember to set `/sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable` to `1` to enable manual fan control.

**Comment by IsaakGroepT** [comment]
Thanks for your message.

My fans stop spinning at `echo "0" > /sys/class/drm/card0/device/hwmon/hwmon2/pwm1`. They start spinning at value 51 or 20% of the fan speed. And yes pwm1_enable is set to 1, even though that doesn't seem to be a requirements because even with value to "auto mode" I can manipulate the fans.
But adding another value below 50k will make the fans start spinning much sooner than the minimum temperate requirement of 60°C, which most GPU manufacturers. Maybe it's better that I modify the script so that the fans keep spinning for a little while after the temperate is dropping a lot in a short time?

**Comment by IsaakGroepT** [comment]
I also want to suggest being a bit more sparingly with the messages while using it as a systemd service because it's spamming the journal completely full.

**Comment by grmat** [comment]
> My fans stop spinning at echo "0" [...] They start spinning at value 51 or 20% of the fan speed.

Doesn't seem right to me. Can you confirm that you tested both ways? If you come from higher values, e.g. PWM is set to `60` and you decrease to `55`, `50`, `45`... fans will continue to spin and not stop before you reach PWM value `0`?

The problem with your setup is that PWM values are interpolated. Looking at your table from above:
If the temperature is decreasing to 59(.000) degrees, PWM will not be set to `0` nor `51` but interpolated between these two. While I'm waiting for your confirmation of the above, I assume that any PWM value <`50` will stop the fans. Therefore, it is only logical that the fans stop when falling below 60 degrees. To illustrate this, let's look at the fan curves. You've set the values as follows:

![set](https://i.imgur.com/Ng8vGWW.png)

But due fan start/stop behaviour, the effective curve is more like:

![effective](https://i.imgur.com/BYQpj5K.png)

While from your explanations, I expect you want something like:

![want](https://i.imgur.com/Huiuafg.png)

Which would ultimately result in:

![result](https://i.imgur.com/wcB4E7j.png)


So, I'd try altering the above table to something like

```
TEMPS=(0 50000 60000 75000 85000 )
PWMS=(0      51    51   153   255 )
```

It will ensure the fans keep spinning at moderate speed between 50 and 60 degrees (which I understand as some kind of transition period for you) and then accelerate above 60 degrees.

You can also try to lower `HYSTERESIS`, as it might introduce negative behaviour due to bad luck and timing. E.g. with the default value of 6000, if the temp is falling and the script lowers the pwm at 65 degrees, it will effectively stop the fans at 59 degrees. But when the temp is lowered at 60 degrees, the fans will stop not before reaching 54 degrees.

**Comment by IsaakGroepT** [comment]
Thanks for the detailed explanation and the graphs to make it clear :1st_place_medal: !

It seems that the actual minimum PWM value for my fans to spin is around 30-35, not 51 like I said before. It's technically the same the other way around. But going down, they stop spinning 59°C as you said, due to the more dominant `HYSTERESIS` setting.

What I actually want to achieve is explained in your fourth graph. Setting the PWM values to 
```
TEMPS=(0 50000 60000 75000 85000 )
PWMS=( 0    51    51   153   255 )
```
is not completely what I want since the fans would have kept spinning at <60°C, which they also do in automatic mode. I realise the spinning is at a minimum and the noise is not easily noticeable, but I'd like a complete stop below a temperature of 60°C. But when I've been gaming, I'd like the fans to slow stop and not abruptly after the temperature reaches 59°C. So as the `HYSTERESIS` is supposed to handle that, maybe I just lower that to a low value (say 2000), but I'm not sure if that would introduce a negative side-effect.

**Comment by grmat** [comment]
Another tip that I can give you, is temporarily set `FILE_TEMP` to something different, for example `/tmp/temperature`. So you could manually write pseudo temperature values into this file and check the script/fan behaviour while trying to figure out your config.

> I'd like a complete stop below a temperature of 60°C. But when I've been gaming, I'd like the fans to slow stop and not abruptly after the temperature reaches 59°C

I imagine that could be achieved by memorising previous values, either 
- store a value of the highest temperature within the last n reads (to detect if you've been gaming) or
- setting the fan curve so that the fans will continue to run until below 50 and add an additional condition for delay if fans have previously been stopped.

**Comment by IsaakGroepT** [comment]
Good idea. I'm currently using your script as provided, except for that I commented out the messages for less journal spam. However, I'm planning to rewrite your script in Python so that I can modify it completely. I'm not much a Bash scripting guy, I can read it but not write it without trouble.

If you're interesting, I can get back to you with the result.

**Comment by grmat** [comment]
Yeah, why not. We can link to your script from here.

There is already a python script for the Radeon Open Compute platform, you might be interested in utilising some of their helper functions. Or start from scratch ;)
https://github.com/RadeonOpenCompute/ROC-smi/blob/master/rocm-smi

**Comment by IsaakGroepT** [comment]
Good tip! Didn't know about that

Thanks again for helping out :1st_place_medal:

**Comment by grmat** [comment]
No worries!

I'm gonna close this issue now, but feel free to come back and link to your project. I might paste the link to the README :wink:
